title: "cRyptonic CTF solves"
remote_theme: pmarsceill/just-the-docs

color_scheme: "light"

search_enabled: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2021 cryp71x3rz. Distributed by an <a href=\"https://github.com/c12yptonic/ctf-writeups/blob/main/LICENSE\">MIT license.</a>"