title: "cRyptonic CTF solves"
remote_theme: pmarsceill/just-the-docs

color_scheme: "light"

search_enabled: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2021 <a href=\"https://ctftime.org/team/135603\">cryp71x3rz</a>. Distributed by an <a href=\"https://github.com/c12yptonic/ctf-writeups/blob/main/LICENSE\">MIT license.</a>
<script>
function getCurrentTheme() {
  let themeVal = localStorage.getItem(\"theme\");
  if (!themeVal) {
    themeVal = \"default\";
  }
  return themeVal;
}

function isCorrectTheme() {
  if (jtd.getTheme() == getCurrentTheme()) {
    return true;
  } else if (jtd.getTheme() == \"default\" && getCurrentTheme() == \"light\") {
    return true;
  } else {
    return false;
  }
}

function toggleTheme() {
  let themeVal = getCurrentTheme();

  if (themeVal == \"light\") {
    themeVal = \"dark\";
  } else {
    themeVal = \"light\";
  }
  localStorage.setItem(\"theme\", themeVal);
  jtd.setTheme(themeVal);
}

/*
document.addEventListener(\"load\", function(){
  if (!isCorrectTheme()) {
    console.log(jtd.getTheme() + \",eventlistener,\" + getCurrentTheme());
    jtd.setTheme(getCurrentTheme());
  }
});
*/
</script>
<style>
.no-vertical-align-c {
  vertical-align: unset !important;
}
</style>"

aux_links:
  "<img alt=\"GitHub issues\" src=\"https://img.shields.io/github/issues/c12yptonic/ctf-writeups\"/>":
    - "https://github.com/c12yptonic/ctf-writeups/issues"
  "<img alt=\"GitHub Repo stars\" src=\"https://img.shields.io/github/stars/c12yptonic/ctf-writeups?color=brightgreen\">":
    - "https://github.com/c12yptonic/ctf-writeups/stargazers"

aux_links_new_tab: true

last_edit_timestamp: true
last_edit_time_format: "%e %b, %Y at %I:%M %p %Z"

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true