title: "cRyptonic CTF solves"
remote_theme: pmarsceill/just-the-docs

color_scheme: "light"

search_enabled: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2021 cryp71x3rz. Distributed by an <a href=\"https://github.com/c12yptonic/ctf-writeups/blob/main/LICENSE\">MIT license.</a>
<script>
function getCurrentTheme() {
  let themeVal = localStorage.getItem(\"theme\");
  if (!themeVal) {
    themeVal = \"light\";
  }
  return themeVal;
}

function isCorrectTheme() {
  if (jtd.getTheme() == getCurrentTheme()) {
    return true;
  } else if (jtd.getTheme() == \"default\" && getCurrentTheme() == \"light\") {
    return true;
  } else {
    return false;
  }
}

function toggleTheme() {
  let themeVal = getCurrentTheme();

  if (themeVal == \"light\") {
    themeVal = \"dark\";
  } else {
    themeVal = \"light\";
  }
  localStorage.setItem(\"theme\", themeVal);
  jtd.setTheme(themeVal);
}

document.addEventListener(\"load\", function(){
  if (!isCorrectTheme()) {
    console.log(jtd.getTheme() + \",eventlistener,\" + getCurrentTheme());
    jtd.setTheme(getCurrentTheme());
  }
});

if (!isCorrectTheme()) {
  console.log(jtd.getTheme() + \",initial,\" + getCurrentTheme());
  jtd.setTheme(getCurrentTheme());
}
</script>"

aux_links:
  "Switch theme":
    - "javascript:toggleTheme()"

aux_links_new_tab: false